version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'student-db'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=softmedialab'
  app:
    build: ./
    container_name: 'student-java'
    ports:
      - 8080:8080
    links:
      - 'postgres:my-db'